spring:
  profiles:
    include: oauth
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
  session:
    store-type: jdbc

spring.h2.console.enabled: false