spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: profile,email,profile_image
            authorization-grant-type: authorization_code
            client-secret: 4o7Lni5tAQ
            client-id: 4PNeWJnLZc0hjuSiJykc
            client-name: Naver
          google:
            client-secret: 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
            client-id: 877795480107-g6e2sj799lrkpds6ka7pc15r8uikc9da.apps.googleusercontent.com
            scope: profile,email
        provider:
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
